apiVersion: v1
kind: Service
metadata:
  name: event-dispatcher-service
spec:
  type : ClusterIP
  selector:
    app: event-dispatcher
  ports:
  - name: ed-svc-port
    protocol: TCP
    port: 8000
    targetPort: ed-port